import os
import json
from typing import Dict, Any, Tuple, Optional
import google.generativeai as genai
from dotenv import load_dotenv

# Load env variables (e.g. from .env file in backend)
load_dotenv()

class SecurityAgentOrchestrator:
    def __init__(self):
        # Retrieve Gemini API key from environment
        self.api_key = os.getenv("GEMINI_API_KEY")
        self.has_real_llm = False
        
        if self.api_key:
            try:
                genai.configure(api_key=self.api_key)
                # We use the highly capable and fast gemini-1.5-flash model
                self.model = genai.GenerativeModel("gemini-1.5-flash")
                self.has_real_llm = True
                print("[Agent Layer] Gemini API successfully configured. Real LLM Reasoning active.")
            except Exception as e:
                print(f"[Agent Layer] WARNING: Failed to configure Gemini client: {e}. Falling back to Rule-Based routing.")
        else:
            print("[Agent Layer] INFO: No GEMINI_API_KEY found in environment. Falling back to Rule-Based semantic routing.")

    async def decide_tool(self, user_message: str, available_tools: list) -> Tuple[Optional[str], dict, str]:
        """
        Determines which tool to execute based on user message and list of available tools.
        Returns:
            chosen_tool: str or None
            arguments: dict
            explanation: str
        """
        # If API key is available, use Gemini to reason about intent
        if self.has_real_llm:
            try:
                return await self._call_gemini_reasoner(user_message, available_tools)
            except Exception as e:
                print(f"[Agent Layer] Gemini invocation failed: {e}. Falling back to rule-based routing.")

        # Fallback Rule-Based Semantic Routing (Simulated Agent Reasoning)
        return self._local_semantic_router(user_message, available_tools)

    async def _call_gemini_reasoner(self, user_message: str, available_tools: list) -> Tuple[Optional[str], dict, str]:
        # Formulate a schema representation of tools to feed into system prompt
        tool_definitions = []
        for tool in available_tools:
            tool_definitions.append({
                "name": tool["name"],
                "description": tool["description"],
                "parameters": tool.get("inputSchema", {})
            })

        system_instruction = (
            "You are an AI Security Agent operating in a Security Operations Center (SOC) dashboard. "
            "You have access to specialized Model Context Protocol (MCP) tools to help investigate threats.\n\n"
            f"AVAILABLE TOOLS:\n{json.dumps(tool_definitions, indent=2)}\n\n"
            "Given the user request, you must analyze their intent and select the most appropriate tool to run. "
            "You must respond with a strictly formatted JSON object. Do not include any markdown fences or explanations outside the JSON.\n\n"
            "JSON SCHEMA FORMAT:\n"
            "{\n"
            '  "chosen_tool": "name_of_tool_or_null",\n'
            '  "arguments": { "arg_name": "arg_value" },\n'
            '  "explanation": "Brief explanation of why you selected this tool and what you hope to discover"\n'
            "}\n\n"
            "Example: If the user says 'Ping 8.8.8.8', you respond:\n"
            "{\n"
            '  "chosen_tool": "ping_host",\n'
            '  "arguments": { "host": "8.8.8.8" },\n'
            '  "explanation": "Checking host reachability for 8.8.8.8 as requested."\n'
            "}"
        )

        prompt = f"User Request: \"{user_message}\"\n\nJSON Response:"
        
        # Invoke Gemini 1.5 Flash
        response = self.model.generate_content(
            contents=[
                {"role": "user", "parts": [system_instruction, prompt]}
            ],
            generation_config={"response_mime_type": "application/json"}
        )

        try:
            decision = json.loads(response.text.strip())
            chosen_tool = decision.get("chosen_tool")
            arguments = decision.get("arguments", {})
            explanation = decision.get("explanation", "Reasoning generated by Gemini LLM.")
            
            # Map clean 'null' or empty string responses to None
            if not chosen_tool or chosen_tool == "null":
                chosen_tool = None
                
            return chosen_tool, arguments, explanation
            
        except Exception as e:
            print(f"[Agent Layer] JSON Parsing of Gemini response failed: {e}. Raw response: {response.text}")
            raise e

    def _local_semantic_router(self, user_message: str, available_tools: list) -> Tuple[Optional[str], dict, str]:
        """
        Clever, rule-based semantic parser that matches keywords to tool definitions.
        Ensures the application works fully even without a Gemini API Key.
        """
        msg = user_message.lower()
        tool_names = [t["name"] for t in available_tools]
        
        # 1. DNS Lookup Router
        if "dns" in msg or "resolve" in msg or "lookup" in msg:
            if "dns_lookup" in tool_names:
                # Basic string parsing to find domain-like strings
                import re
                domains = re.findall(r'\b[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\b', msg)
                target = domains[0] if domains else "google.com"
                return (
                    "dns_lookup",
                    {"domain": target},
                    f"[Local Router] I analyzed the request and detected domain keyword. Selected dns_lookup tool for host '{target}'."
                )

        # 2. Ping Router
        if "ping" in msg or "reach" in msg or "alive" in msg:
            if "ping_host" in tool_names:
                import re
                ips_or_domains = re.findall(r'\b[a-zA-Z0-9.-]+\.[a-zA-Z0-9.-]+\b', msg)
                ips_or_domains = [x for x in ips_or_domains if x not in ["ping", "resolve", "reach", "alive"]]
                target = ips_or_domains[0] if ips_or_domains else "8.8.8.8"
                return (
                    "ping_host",
                    {"host": target},
                    f"[Local Router] I analyzed the request and detected connection keyword. Selected ping_host tool for target '{target}'."
                )

        # 3. GeoIP Lookup Router
        if "geo" in msg or "location" in msg or "locate" in msg or "where" in msg:
            if "geoip_lookup" in tool_names:
                import re
                ips = re.findall(r'\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b', msg)
                target = ips[0] if ips else "8.8.8.8"
                return (
                    "geoip_lookup",
                    {"ip": target},
                    f"[Local Router] I analyzed the request and detected location query. Selected geoip_lookup tool for IP '{target}'."
                )

        # 4. IP/Domain Reputation Catch-all Router
        if "safe" in msg or "malicious" in msg or "threat" in msg or "check" in msg or "reputation" in msg or "abuse" in msg or "blacklist" in msg:
            import re
            ips = re.findall(r'\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b', msg)
            if ips and "analyze_ip_reputation" in tool_names:
                return (
                    "analyze_ip_reputation",
                    {"ip": ips[0]},
                    f"[Local Router] I analyzed the request and detected IP reputation check. Selected analyze_ip_reputation tool for IP '{ips[0]}'."
                )
            
            domains = re.findall(r'\b[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\b', msg)
            domains = [d for d in domains if not re.match(r'^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$', d)]
            if domains and "analyze_domain_reputation" in tool_names:
                # Filter out stop words
                stop_words = ["dns", "ping", "lookup", "resolve", "domain", "reputation", "threat", "check", "malicious", "safe", "blacklist"]
                valid_domains = [d for d in domains if d not in stop_words]
                target = valid_domains[0] if valid_domains else domains[0]
                return (
                    "analyze_domain_reputation",
                    {"domain": target},
                    f"[Local Router] I analyzed the request and detected domain reputation check. Selected analyze_domain_reputation tool for domain '{target}'."
                )

        # 5. Log Analysis Router
        if "parse log" in msg or "analyze log" in msg or "auth log" in msg or "read log" in msg or "authentication log" in msg:
            if "analyze_authentication_logs" in tool_names:
                return (
                    "analyze_authentication_logs",
                    {},
                    "[Local Router] I analyzed the request and detected log parsing keyword. Selected analyze_authentication_logs tool."
                )

        # 6. Brute Force Router
        if "brute force" in msg or "brute-force" in msg or "failed attempt" in msg or "login attack" in msg or "multiple failure" in msg:
            if "detect_brute_force" in tool_names:
                return (
                    "detect_brute_force",
                    {},
                    "[Local Router] I analyzed the request and detected brute force query. Selected detect_brute_force tool."
                )

        # 7. Impossible Travel Router
        if "impossible travel" in msg or "travel anomaly" in msg or "multi-country login" in msg or "location anomaly" in msg:
            if "detect_impossible_travel" in tool_names:
                return (
                    "detect_impossible_travel",
                    {},
                    "[Local Router] I analyzed the request and detected impossible travel query. Selected detect_impossible_travel tool."
                )

        # 8. Off-Hours Login Router
        if "off hour" in msg or "off-hours" in msg or "late night login" in msg or "suspicious hour" in msg:
            if "detect_off_hours_logins" in tool_names:
                return (
                    "detect_off_hours_logins",
                    {},
                    "[Local Router] I analyzed the request and detected off-hours login query. Selected detect_off_hours_logins tool."
                )

        # No matching tool found
        explanation = (
            "I parsed your request, but I could not find a suitable security tool to execute.\n"
            "Try asking me to 'Ping 8.8.8.8', 'Find location for 8.8.8.8', 'Parse auth logs', 'Scan for brute-force attacks', or 'Check for impossible travel anomalies'!"
        )
        if not self.api_key:
            explanation += "\n\n*(Tip: Set a GEMINI_API_KEY in a .env file to enable dynamic AI reasoning!)*"
            
        return None, {}, explanation

# App-wide singleton instance of the agent
agent_orchestrator = SecurityAgentOrchestrator()
